### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Users/.../Documents/weex_project/yanxuan-weex-demo/plugins/plugins.json'

### ISSUE THREAD

**Issue by MiWi-Lin** [zwwill/yanxuan-weex-demo#66]
# 一句话概括
执行```weex platform add ios```` success后出现错误
# 详细描述
```
11:44:18 : Adding ios weexpack-ios@4.1.6 ...
11:44:18 : Success!
11:44:18 : Error: ENOENT: no such file or directory, open '/Users/.../Documents/weex_project/yanxuan-weex-demo/plugins/plugins.json'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at installForNewPlatform (/Users/.../.xtoolkit/node_modules/weexpack/lib/plugin/install.js:87:35)
    at /Users/miwi/.xtoolkit/node_modules/weexpack/lib/platform/index.js:219:9
    at _fulfilled (/Users/.../.xtoolkit/node_modules/weexpack/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/.../.xtoolkit/node_modules/weexpack/node_modules/q/q.js:816:30)
```
# 重现（选）

**Comment by zwwill** [comment]
清理下 platform 目录重新构建试试

**Comment by MiWi-Lin** [comment]
``` weex platform remove ios``` success后，再add也是，yanxuan-weex-demo/plugins/plugins.json这个文件是否被ignore了？

**Comment by zwwill** [comment]
工程下没有这个文件，可能是使用了新的toolkit导致的依赖关系。你使用weexpack 新建一个工程，然后将源码copy过去试试。

**Comment by MiWi-Lin** [comment]
好的
