### ISSUE TITLE
Entry, ":CFBundleIdentifier", Does Not Exist 错误

### ISSUE THREAD

**Issue by MiWi-Lin** [zwwill/yanxuan-weex-demo#67]
# 一句话概括
在另一个[issues 66](https://github.com/zwwill/yanxuan-weex-demo/issues/66)提示下，运行```weex run ios```后出现错误
# 详细描述
```
11:49:10 : Run iOS Simulator..
Print: Entry, ":CFBundleIdentifier", Does Not Exist
11:49:10 : Error:Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/WeexDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:575:11)
    at Object.execFileSync (child_process.js:593:13)
    at _runAppOnSimulator (/Users/.../.xtoolkit/node_modules/weexpack/lib/run/ios.js:411:18)
    at /Users/.../.xtoolkit/node_modules/weexpack/lib/run/ios.js:375:7
    at new Promise (<anonymous>)
    at runApp (/Users/.../.xtoolkit/node_modules/weexpack/lib/run/ios.js:373:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

按照这个[Weex 解决Print: Entry, ":CFBundleIdentifier", Does Not Exist 错误方法](http://www.bubuko.com/infodetail-2324561.html)内提到的三个文件下载后均无效

**Comment by MiWi-Lin** [comment]
对**ios.config.json**重新设置AppName、AppId后运行成功

**Comment by zwwill** [comment]
正常情况下，weex是使用是单页的，框架由原生人员开发，前端开发人员只需要开发每个页面即可，像这种全栈式的开发模式不是weex的特长。此demo只是做了一个特殊的尝试
